# Generated by Django 6.0.3 on 2026-04-02 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=False, verbose_name='تاجر')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('baladia', models.CharField(blank=True, max_length=100, verbose_name='البلدية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المتجر')),
                ('store_description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('store_category', models.CharField(blank=True, max_length=100, verbose_name='فئة المتجر')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='شعار المتجر')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
