# Generated by Django 6.0.3 on 2026-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='TRK91244331', max_length=50, null=True, verbose_name='رقم التتبع'),
        ),
    ]
