# Generated by Django 6.0.3 on 2026-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_category_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='TRK83050629', max_length=50, null=True, verbose_name='رقم التتبع'),
        ),
    ]
