# Generated by Django 6.0.3 on 2026-04-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='TRK78503573', max_length=50, null=True, verbose_name='رقم التتبع'),
        ),
    ]
