# Generated by Django 6.0.3 on 2026-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
            ],
        ),
    ]
