# Generated by Django 6.0.3 on 2026-04-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_subscriptemail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
