# Generated by Django 6.0.3 on 2026-04-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/%Y/%m/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='النص البديل')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='store.product', verbose_name='المنتج')),
                ('variants', models.ManyToManyField(blank=True, related_name='images', to='store.productvariant', verbose_name='المتغيرات المرتبطة')),
            ],
            options={
                'verbose_name': 'صورة متغير',
                'verbose_name_plural': 'صور المتغيرات',
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
