# Generated by Django 6.0.3 on 2026-04-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_productvariant_image_variantimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
