# Generated by Django 6.0.3 on 2026-03-28 15:04

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'الفئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'متغير المنتج', 'verbose_name_plural': 'متغيرات المنتجات'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='صورة المتغير'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم المتغير'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariant', verbose_name='المتغير'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='المواصفات'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='store.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='رمز المتغير'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='المخزون'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(upload_to='products/videos/', verbose_name='فيديو'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
